### ISSUE TITLE
There is a error while add parameter "--ibf_threshold 0.5" in command line

### ISSUE THREAD

**Issue by 276562578** [rmarkello/abagen#206]
There is a error while add parameter `--ibf_threshold 0.5` in command line
```bash
Traceback (most recent call last):
  File "/usr/local/bin/abagen", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/abagen/cli/run.py", line 365, in main
    expression = get_expression_data(atlas=opts.atlas,
  File "/usr/local/lib/python3.10/dist-packages/abagen/allen.py", line 437, in get_expression_data
    probe_info = probes_.filter_probes(flatten_dict(files, 'pacall'),
  File "/usr/local/lib/python3.10/dist-packages/abagen/probes_.py", line 103, in filter_probes
    threshold = np.clip(threshold, 0.0, 1.0)
  File "<__array_function__ internals>", line 5, in clip
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 2115, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 159, in _clip
    return _clip_dep_invoke_with_casting(
  File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 113, in _clip_dep_invoke_with_casting
    return ufunc(*args, out=out, **kwargs)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'clip' did not contain a loop with signature matching types (dtype('<U3'), dtype('float64'), dtype('float64')) -> None
```

**Comment by 276562578** [comment]
And same problem while using `--donors all`, seems the program can't recognize the `all`
